### ISSUE TITLE
Use method chaining

### ISSUE THREAD

**Issue by vladshcherbin** [keenwon/koa-subdomain#2]
In koa it's possible to chain `use`:

```js
app
  .use(firstMiddleware())
  .use(secondMiddleware())
  .listen(3000)
```

Is it possible to make `subdomain.use('one', router).use('two', router)` ?

**Comment by keenwon** [comment]
Yes, of course.
tomorrow maybe. I will release a new version to support this.

**Comment by keenwon** [comment]
https://github.com/keenwon/koa-subdomain/blob/master/test/lib/subdomainRouter.js#L26

try 2.1.0

**Comment by vladshcherbin** [comment]
@keenwon works for me. Thank you! 👍
