### ISSUE TITLE
Subdomain middleware

### ISSUE THREAD

**Issue by vladshcherbin** [keenwon/koa-subdomain#4]
Hey, is it somehow possible to use middleware per subdomain and not per app?

**Comment by keenwon** [comment]
I don't really understand your question.

Is this not use middleware per subdomain?

```js
const app = require('koa')();
const subdomain = require('koa-subdomain')();

// one.example.com
subdomain.use('one', router1);

// two.example.com
subdomain.use('two', router2);

subdomain
  .use('a.one', router3)  // a.one.example.com
  .use('b.one', router4); // b.one.example.com

// example.com
subdomain.use('', router5);

// *.example.com
subdomain.use('*', router6);

// *.one.example.com
subdomain.use('*.one', router7);

// one.*.example.com
subdomain.use('one.*', router8);

app.use(subdomain.routes());
app.listen(8888);
```

**Comment by vladshcherbin** [comment]
@keenwon yes, in `subdomain.use('one', router1)` router 1 is a middleware, for router. How is it possible to add another middleware, to execute before `router1` middleware. Something like this one?

```js
subdomain.use('one', beforeRouterMiddleware)
subdomain.use('one', router1)
subdomain.use('one', afterRouterMiddleware)
```

**Comment by keenwon** [comment]
`router1` is instance of [koa-router)](https://github.com/alexmingoia/koa-router). maybe you can use [router.use](https://github.com/alexmingoia/koa-router#module_koa-router--Router+use).

Example

```js
// session middleware will run before authorize
router
  .use(session())
  .use(authorize());

// use middleware only with given path
router.use('/users', userAuth());

// or with an array of paths
router.use(['/users', '/admin'], userAuth());

app.use(router.routes());
```

**Comment by vladshcherbin** [comment]
@keenwon yep, I've tried multiple middlewares with `subdomain.use()` and failed. Didn't try this with router. 🤦‍♂️ 

Router middleware works for my use-case, thank you!
