### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by leumasme** [keenwon/koa-subdomain#86]
Hello
Could you please add basic Typescript typings so that it is easier to use this in typescript projects?
Thanks

**Comment by BolZer** [comment]
@leumasme A bit late but here:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52090

You could just pull the type definition from the PR or just wait a bit until the PR is merged and the types are available via
@types/koa-subdomain

**Comment by leumasme** [comment]
Many thanks!
